commands:
#  - file_name: show_run
    #command_: show run
    #del_list_file: show_run_del_ist.txt
- file_name: show_version
  command_: show version
  template_file: cisco_ios_show_version.textfsm
  del_list_file: show_version_del_list.txt
- file_name: show_ip_route
  command: show ip route
  template_file: cisco_ios_show_ip_route.textfsm
  del_list_file: show_ip_route_del_list.txt
- file_name: show_vlan
  command: show vlan
  template_file: cisco_ios_show_vlan.textfsm
  del_list_file: show_vlan_del_list.txt
- file_name: show_ip_ospf_neighbor
  command: show ip ospf neighbor
  template_file: cisco_ios_show_ip_ospf_neighbor.textfsm
  del_list_file: show_ip_ospf_neighbor_del_list.txt
- file_name: show_vrf
  command: show vrf
  template_file: cisco_ios_show_vrf.textfsm
  del_list_file: show_vrf_del_list.txt
- file_name: show_spanning-tree
  command: show spanning-tree
  template_file: cisco_ios_show_spanning-tree.textfsm
  del_list_file: show_spanning-tree_del_list.txt
  del_list_file: show_vrf_del_list.txt
- file_name: show_spanning-tree
  command: show spanning-tree
  template_file: cisco_ios_show_spanning-tree.textfsm

#text用の加工指定 
        
process_file:
  - process_command: show_run
    cmd_process_file: process_show_run_del_list.txt


