commands:
#  - file_name: show_run
    #command_: show run
    #del_list_file: show_run_del_ist.txt
- file_name: show_version
  command_: show version
  template_file: cisco_ios_show_version.textfsm
- file_name: show_ip_route
  command: show ip route
  template_file: cisco_ios_show_ip_route.textfsm
  del_list_file: show_ip_route_del_list.txt

#text用の加工指定 
        
process_file:
  - process_command: show_run
    cmd_process_file: process_show_run_del_list.txt


