commands:
#  - file_name: show_run
    #command_: show run
    #del_list_file: show_run_del_ist.txt
- file_name: show_version
  command_: show version
  template_file: cisco_xr_show_version.textfsm
  del_list_file: xr_show_version_del_list.txt
- file_name: show_ip_interface_brief
  command: show ip interface brief
  template_file: cisco_xr_show_ip_interface_brief.textfsm
  del_list_file: xr_show_ip_int_brief_del_list.txt
- file_name: show_ospf_neighbor
  command: show ospf neighbor
  template_file: cisco_xr_show_ospf_neighbor.textfsm
  del_list_file: xr_show_ospf_neighbor_del_list.txt
- file_name: admin_show_platform
  command: admin show platform
  template_file: co_xr_admin_show_platform.textfsm
  del_list_file: xr_admin_show_platform_del_list.txt
- file_name: show_ip_route
  command: admin show ip route
  template_file: cisco_xr_show_ip_route.textfsm
  del_list_file: xr_show_ip_route_del_list.txt

#text用の加工指定 
        
process_file:
  - process_command: show_run
    cmd_process_file: process_show_run_del_list.txt


