---
- name: save show
  copy:
    content: "{{ show_results | to_nice_json }}"
    dest: "{{ logdir.path }}/{{ inventory_hostname }}_{{ commands_show }}"
  #loop: "{{ results }}"
  delegate_to: localhost
  no_log: True


- name: save route
  copy:
    content: "{{ route_results | to_nice_json }}"
    dest: "{{ logdir.path }}/{{ inventory_hostname }}_{{ commands_route }}"
  #loop: "{{ results }}"
   delegate_to: localhost
   no_log: True

