---
- name: save show
  copy:
    content: "{{ show_result | to_nice_json }}"
    dest: "{{ logdir.path }}/{{ inventory_hostname }}_{{ commands_show }}"
  #loop: "{{ show_results }}"
  delegate_to: localhost
  no_log: True

- name: save route
  copy:
    content: "{{ route_result | to_nice_json }}"
    dest: "{{ logdir.path }}/{{ inventory_hostname }}_{{ commands_route }}"
  #loop: "{{ route_results }}"
  delegate_to: localhost
  no_log: True

