---
#ansible_user: #ユーザー名記載 #マスク処理
#ansible_password: #パスワード記載 #マスク処理

commands:
#  - file_name: show_running-config
#    command_: show running-config
#  - file_name: show_controller
#    command_: show controller
#  - file_name: show_versions
#    command_: show versions
# insert
  - file_name: show_ip_interface_physical
    command_: show interface brief xxxxx physical
    template_file: show_ip_interface_physical.template
    del_list_file: show_ip_interface_physical_list.txt

  - file_name: show_ip_interface_po1
    command_: show interface brief xxxxx aggregated po1
    template_file: show_ip_interface_po1.template
    del_list_file: show_ip_interface_po1_list.txt

  - file_name: show_inventory
    command_: show inventory xxxxx

  - file_name: show_environment
    command_: show environment xxxxx
    template_file: show_environment.template
    del_list_file: show_environment_list.txt

  - file_name: show_run_all
    command_: show running-config all

  - file_name: show_bgp_sessions
    command_: show bgp sessions xxxxx vrf xxxxx

  - file_name: show_controller
    command_: show controller xxxxx processes
